#SPDX-License-Identifier: MIT-0
---
# tasks file for updatenginx_role
- name: Change nginx port (IPv4)
  replace:
    path: /etc/nginx/sites-available/default
    regexp: 'listen\s+80'
    replace: 'listen 81'
  notify: 
    - Validate nginx config
    - Restart nginx

- name: Change nginx port (IPv6)
  replace:
    path: /etc/nginx/sites-available/default
    regexp: 'listen\s+\[::\]:80'
    replace: 'listen [::]:81'
  notify: 
    - Validate nginx config
    - Restart nginx
