#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/docker_role

docker_repo: "https://download.docker.com/linux/ubuntu"
docker_gpg: "https://download.docker.com/linux/ubuntu/gpg"


docker_packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
 
docker_dependencies:
    - ca-certificates 
    - curl
    - gnupg