#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx_role
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true